name: Notify Mattermost on Push

on:
  push:
    branches: ["**"]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure jq is available
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build payload JSON safely
        run: |
          REPO="${GITHUB_REPOSITORY}"
          BRANCH="${GITHUB_REF_NAME}"
          ACTOR="${GITHUB_ACTOR}"
          COMMITS=$(jq -r '.commits | map("- " + .message + " (" + .id[0:7] + ")") | join("\n")' <<< '${{ toJson(github.event) }}')
          [ -z "$COMMITS" ] && COMMITS="- (no commit messages)"

          TEXT="ðŸ“¢ *${REPO}*ì— push ë°œìƒ
ë¸Œëžœì¹˜: \`${BRANCH}\`
ìž‘ì„±ìž: ${ACTOR}

${COMMITS}"

          # jqë¡œ ì˜¬ë°”ë¥¸ JSON ìƒì„± â†’ payload.json
          jq -n --arg t "$TEXT" '{text:$t}' > payload.json
          echo "==== payload.json ===="
          cat payload.json

      - name: Send to Mattermost
        env:
          HOOK: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        run: |
          curl -sS -X POST "$HOOK" \
            -H 'Content-Type: application/json' \
            --data-binary @payload.json
